# Generated by Django 4.1.7 on 2023-04-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enrolled_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=25)),
                ('device_id', models.IntegerField(max_length=25)),
                ('device_brand', models.CharField(max_length=25)),
                ('policy_name', models.CharField(max_length=25)),
                ('lock_status', models.CharField(max_length=25)),
                ('qrCode', models.FileField(max_length=25, upload_to='')),
            ],
        ),
    ]
