# Generated by Django 4.1.7 on 2023-04-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled_device',
            name='qrCode',
        ),
        migrations.AlterField(
            model_name='enrolled_device',
            name='customer_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='enrolled_device',
            name='device_brand',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='enrolled_device',
            name='device_id',
            field=models.IntegerField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='enrolled_device',
            name='lock_status',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='enrolled_device',
            name='policy_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='enrolled_device',
            name='qrcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
