# Generated by Django 4.1.7 on 2023-04-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_enrollment', '0002_remove_enrolled_device_qrcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled_device',
            name='lock_status',
            field=models.CharField(default=False, max_length=25, null=True),
        ),
    ]
